// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The CLI (db push, migrate, studio) needs the direct, non-pooled
    // connection — Supabase's pooler (PgBouncer, transaction mode) can't
    // run the multi-statement DDL these commands issue. The app itself
    // uses the pooled DATABASE_URL instead — see lib/prisma.ts, which
    // passes it straight to the PrismaPg adapter, bypassing this config.
    url: process.env["DIRECT_URL"],
  },
});
