import type { CatalogEntry } from "./types";

export const CATALOG_TYPES = ["All", "R-410A", "R-32", "R-134a", "R-404A", "R-407C"];

// Listing-page view of the catalog. Several SKUs here are just different
// weight tiers of a product already modeled in lib/productDetails.ts, so
// each entry carries the canonical productId + weightId it should deep-link
// to (see app/product/[id]/page.tsx's `weight` search param).
export const CATALOG: CatalogEntry[] = [
  {
    id: 1,
    name: "R-410A Premium",
    type: "R-410A",
    weight: 25,
    price: 189,
    sku: "410A-25",
    dbSku: "HC-R410A-25",
    tag: "Best seller",
    note: "Virgin · Puron blend",
    productId: 1,
    weightId: "25",
  },
  {
    id: 2,
    name: "R-410A Bulk",
    type: "R-410A",
    weight: 100,
    price: 618,
    sku: "410A-100",
    dbSku: "HC-410A-100",
    tag: "",
    note: "Virgin · recovery ready",
    productId: 1,
    weightId: "100",
  },
  {
    id: 3,
    name: "R-32 Low GWP",
    type: "R-32",
    weight: 25,
    price: 212,
    sku: "R32-25",
    dbSku: "HC-R32-25",
    tag: "Low GWP",
    note: "A2L rated · single component",
    productId: 3,
    weightId: "25",
  },
  {
    id: 4,
    name: "R-134a Standard",
    type: "R-134a",
    weight: 30,
    price: 164,
    sku: "134A-30",
    dbSku: "HC-R134A-30",
    tag: "",
    note: "Chillers & automotive",
    productId: 2,
    weightId: "30",
  },
  {
    id: 5,
    name: "R-404A Reclaimed",
    type: "R-404A",
    weight: 24,
    price: 298,
    sku: "404A-24",
    dbSku: "HC-404A-24",
    tag: "Reclaimed",
    note: "AHRI-700 verified",
    productId: 4,
    weightId: "24",
  },
  {
    id: 6,
    name: "R-407C Service",
    type: "R-407C",
    weight: 25,
    price: 236,
    sku: "407C-25",
    dbSku: "HC-407C-25",
    tag: "",
    note: "R-22 retrofit blend",
    productId: 6,
    weightId: "25",
  },
  {
    id: 7,
    name: "R-134a Bulk",
    type: "R-134a",
    weight: 50,
    price: 268,
    sku: "134A-50",
    dbSku: "HC-134A-50",
    tag: "",
    note: "Virgin · fleet service",
    productId: 2,
    weightId: "50",
  },
  {
    id: 8,
    name: "R-32 Bulk",
    type: "R-32",
    weight: 50,
    price: 398,
    sku: "R32-50",
    dbSku: "HC-R32-50",
    tag: "",
    note: "A2L rated · low GWP",
    productId: 3,
    weightId: "50",
  },
  {
    id: 9,
    name: "R-410A Service Pack",
    type: "R-410A",
    weight: 50,
    price: 342,
    sku: "410A-50",
    dbSku: "HC-410A-50",
    tag: "",
    note: "Virgin · sealed valve",
    productId: 1,
    weightId: "50",
  },
  {
    id: 10,
    name: "R-407C Bulk",
    type: "R-407C",
    weight: 100,
    price: 742,
    sku: "407C-100",
    dbSku: "HC-407C-100",
    tag: "",
    note: "R-22 retrofit blend",
    productId: 6,
    weightId: "100",
  },
  {
    id: 11,
    name: "R-404A Virgin",
    type: "R-404A",
    weight: 50,
    price: 512,
    sku: "404A-50",
    dbSku: "HC-404A-50",
    tag: "",
    note: "Commercial refrigeration",
    productId: 5,
    weightId: "50",
  },
  {
    id: 12,
    name: "R-134a Compact",
    type: "R-134a",
    weight: 25,
    price: 148,
    sku: "134A-25",
    dbSku: "HC-134A-25",
    tag: "",
    note: "Virgin · light service",
    productId: 2,
    weightId: "25",
  },
];
